openapi: 3.0.3
info:
  title: Customer API Specification
  version: 1.0.0
  description: API thông tin chi tiết và hồ sơ Khách hàng.
paths:
  /customers/me:
    get:
      summary: Lấy thông tin cá nhân khách hàng hiện tại
      responses:
        '200':
          description: Thành công
    put:
      summary: Cập nhật thông tin cá nhân khách hàng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                avatarUrl:
                  type: string
      responses:
        '200':
          description: Cập nhật thành công
