openapi: 3.0.3
info:
  title: Notification API Specification
  version: 1.0.0
  description: API gửi và hiển thị thông báo.
paths:
  /notifications:
    get:
      summary: Lấy danh sách thông báo của người dùng
      responses:
        '200':
          description: Thành công

  /notifications/{id}/read:
    patch:
      summary: Đánh dấu đã đọc thông báo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
